Add appraisals for Rails 6.1
Rails 6.1 requires an upgrade to rspec-rails 4.0.0 which fixes a
WrongScopeError: https://github.com/rspec/rspec-rails/pull/2215
Rspec-rails 4.0.0 dropped support for Rails below 5.0, so Rails 4
has been removed from the appraisals.